import { Language } from "../i18n";

export const stopOverthinkingNightContent: Record<Language, any> = {
  en: {
    category: "Mental Health",
    title: "How to Stop Overthinking at Night: 6 Evidence-Based Techniques",
    subtitle: "If your mind gets louder at bedtime, you are not broken. Nighttime rumination is common and trainable with the right tools.",
    date: "April 7, 2026",
    readTime: "8 min read",
    backToPost: "Back to Blog",
    continueReading: "Continue Reading",
    downloadCTA: { title: "Quiet Your Mind with ShineMind", subtitle: "Use guided wind-down audio and journaling prompts to reduce nighttime mental noise.", button: "Download ShineMind" },
    relatedPosts: { anxiety: "How to Manage Anxiety: 8 Evidence-Based Techniques That Work", anxietyDesc: "Build calm during the day and night ->", journal: "How to Start a Gratitude Journal", journalDesc: "Use writing to clear mental clutter ->" },
    content: {
      whyMatters: { title: "Why Overthinking Peaks at Night", intro: "At night, external stimulation drops and unresolved thoughts become louder. Fatigue also weakens cognitive control, making worry loops easier to enter. The solution is not forcing your brain to be blank; it is giving it a safer task." },
      science: { title: "What Helps Most", description: "Cognitive defusion, scheduled worry time, expressive writing, breath regulation, and stimulus control are all supported in anxiety and insomnia protocols. Repetition matters more than perfection." },
      techniques: [
        { title: "1. Brain Dump Before Bed", description: "Writing reduces mental load and looping thoughts.", howTo: "Spend 5 minutes listing worries + one next action for tomorrow." },
        { title: "2. Set a Worry Window", description: "Contain rumination to daytime instead of bedtime.", howTo: "Schedule 15 minutes in late afternoon for worry review." },
        { title: "3. Label Thoughts, Don't Fight Them", description: "Distance lowers emotional fusion with thoughts.", howTo: "Say: 'I am having the thought that...' and return to breath." },
        { title: "4. Use a Sleep Anchor Phrase", description: "A repeated phrase reduces cognitive wandering.", howTo: "Repeat a neutral line slowly with your exhale for 2-3 minutes." },
        { title: "5. If Awake >20 Minutes, Reset", description: "Staying in bed while frustrated conditions wakefulness.", howTo: "Get up briefly, keep lights low, do calm activity, return when sleepy." },
        { title: "6. Reduce Late Information Input", description: "News and social media can trigger cognitive arousal.", howTo: "Create a digital cutoff at least 45 minutes before bed." }
      ],
      buildingResilience: { title: "Nighttime Stability Plan", strategies: [{ label: "Use the same order nightly", text: "Predictability helps your brain feel safe." }, { label: "Measure process", text: "Track whether you did the routine, not just sleep outcome." }, { label: "Get daytime support", text: "Daytime stress regulation reduces nighttime overthinking." }] },
      conclusion: { title: "A Quiet Mind Is Trained, Not Forced", text: "You cannot argue your way to sleep. Use structure, repetition, and gentle redirection. Small nightly reps can significantly reduce overthinking over time." }
    }
  },
  ja: { category: "メンタルヘルス", title: "夜の考えすぎを止める方法：エビデンスに基づく6つの技法", subtitle: "就寝時に思考が加速するのは珍しくありません。適切な方法で改善できます。", date: "2026年4月7日", readTime: "8分で読める", backToPost: "ブログに戻る", continueReading: "続きを読む", downloadCTA: { title: "ShineMindで思考を静める", subtitle: "就寝前オーディオとジャーナリングで夜の雑念を減らします。", button: "ShineMindをダウンロード" }, relatedPosts: { anxiety: "不安管理：効果的な8つの技法", anxietyDesc: "昼夜の落ち着きを育てる ->", journal: "感謝日記の始め方", journalDesc: "書くことで思考を整理 ->" }, content: { whyMatters: { title: "なぜ夜に反すうが強まるのか", intro: "夜は刺激が減り、未解決の思考が目立ちます。疲労で認知制御も弱まり、心配ループに入りやすくなります。" }, science: { title: "有効な方法", description: "思考との距離取り、心配時間の設定、表出筆記、呼吸調整、刺激制御は不眠・不安の文脈で有効性があります。" }, techniques: [{ title: "1. 就寝前ブレインダンプ", description: "書き出しで思考負荷を下げる。", howTo: "5分で不安を書き、明日の1行動を添える。" }, { title: "2. 心配ウィンドウ設定", description: "反すうを日中に限定する。", howTo: "夕方に15分だけ心配レビュー時間を取る。" }, { title: "3. 思考をラベル化", description: "戦うより距離を取る。", howTo: "『〜という考えが浮かんでいる』と表現して呼吸へ戻る。" }, { title: "4. 睡眠アンカーフレーズ", description: "反復語で注意を安定化。", howTo: "呼気に合わせ中立な短文を2-3分繰り返す。" }, { title: "5. 20分以上眠れない時はリセット", description: "焦ってベッドに居続けると覚醒学習が進む。", howTo: "一度起き、暗い環境で静かな行動後に戻る。" }, { title: "6. 夜の情報入力を減らす", description: "ニュース/SNSは覚醒を高める。", howTo: "就寝45分前にデジタル遮断。" }], buildingResilience: { title: "夜の安定プラン", strategies: [{ label: "同じ順序で実施", text: "予測可能性は安心信号になる。" }, { label: "結果より実行を記録", text: "眠れたかよりルーティン実行を追う。" }, { label: "日中の調整も行う", text: "日中ストレスが夜思考に直結する。" }] }, conclusion: { title: "静かな心は訓練できる", text: "睡眠は説得ではなく設計です。優しく繰り返し戻ることで、夜の反すうは減らせます。" } } },
  ko: { category: "정신 건강", title: "밤에 과생각 멈추는 법: 근거 기반 6가지 기술", subtitle: "잠자리에 누우면 생각이 커지는 것은 흔한 일입니다. 올바른 방법으로 줄일 수 있습니다.", date: "2026년 4월 7일", readTime: "8분 읽기", backToPost: "블로그로 돌아가기", continueReading: "계속 읽기", downloadCTA: { title: "ShineMind로 마음 진정", subtitle: "취침 전 오디오와 저널링으로 밤의 잡음을 줄이세요.", button: "ShineMind 다운로드" }, relatedPosts: { anxiety: "불안 관리 방법: 효과적인 8가지 과학 기반 기법", anxietyDesc: "낮과 밤의 안정감 만들기 ->", journal: "감사 일기 시작하는 방법", journalDesc: "글쓰기로 머릿속 정리 ->" }, content: { whyMatters: { title: "왜 밤에 과생각이 심해질까", intro: "밤에는 외부 자극이 줄어 미해결 생각이 더 커집니다. 피로로 인지 제어도 약해집니다." }, science: { title: "도움되는 방법", description: "생각 거리두기, 걱정 시간 설정, 글쓰기, 호흡 조절, 자극 통제가 효과적입니다." }, techniques: [{ title: "1. 취침 전 브레인 덤프", description: "적어내면 루프가 줄어듭니다.", howTo: "5분간 걱정 목록 + 내일 한 가지 행동 적기." }, { title: "2. 걱정 시간 예약", description: "걱정을 밤이 아닌 낮으로 이동.", howTo: "오후에 15분 걱정 리뷰 시간." }, { title: "3. 생각 라벨링", description: "생각과 싸우지 말고 거리두기.", howTo: "'~라는 생각이 떠오른다'라고 말하고 호흡으로 복귀." }, { title: "4. 수면 앵커 문구", description: "반복 문구가 주의 분산을 줄임.", howTo: "숨 내쉴 때 중립 문구를 2-3분 반복." }, { title: "5. 20분 이상 깨어 있으면 리셋", description: "답답한 채 침대에 있으면 각성이 학습됨.", howTo: "잠시 일어나 조도 낮춰 조용한 행동 후 졸릴 때 복귀." }, { title: "6. 늦은 정보 입력 줄이기", description: "뉴스/SNS는 인지 각성을 높임.", howTo: "취침 45분 전 디지털 컷오프." }], buildingResilience: { title: "야간 안정 플랜", strategies: [{ label: "같은 순서 유지", text: "예측 가능성이 안전 신호가 됩니다." }, { label: "결과보다 실행 추적", text: "잠 결과보다 루틴 수행을 체크." }, { label: "낮 조절도 함께", text: "낮 스트레스가 밤 과생각으로 이어집니다." }] }, conclusion: { title: "고요한 마음은 훈련된다", text: "잠은 억지로 되는 게 아닙니다. 구조와 반복이 밤의 과생각을 줄입니다." } } },
  vi: { category: "Sức Khỏe Tâm Thần", title: "Cách Ngừng Suy Nghĩ Quá Mức Vào Ban Đêm: 6 Kỹ Thuật Có Bằng Chứng", subtitle: "Nếu đầu óc ồn hơn khi lên giường, đó là điều rất phổ biến và có thể cải thiện.", date: "7 tháng 4, 2026", readTime: "8 phút đọc", backToPost: "Quay Lại Blog", continueReading: "Tiếp Tục Đọc", downloadCTA: { title: "Làm Dịu Tâm Trí Với ShineMind", subtitle: "Dùng audio thư giãn và gợi ý viết để giảm nhiễu tinh thần ban đêm.", button: "Tải Xuống ShineMind" }, relatedPosts: { anxiety: "Cách Quản Lý Lo Âu: 8 Kỹ Thuật Dựa Trên Bằng Chứng", anxietyDesc: "Xây bình tĩnh cả ngày lẫn đêm ->", journal: "Cách Bắt Đầu Nhật Ký Biết Ơn", journalDesc: "Viết để dọn bớt suy nghĩ ->" }, content: { whyMatters: { title: "Vì Sao Nghĩ Quá Mức Tăng Vào Đêm", intro: "Ban đêm ít kích thích bên ngoài, nên suy nghĩ chưa giải quyết trở nên lớn hơn. Mệt mỏi cũng làm giảm kiểm soát nhận thức." }, science: { title: "Điều Gì Hiệu Quả", description: "Khoảng cách với suy nghĩ, khung giờ lo lắng, viết biểu đạt, điều hòa hơi thở và kiểm soát kích thích đều hữu ích." }, techniques: [{ title: "1. Xả Não Trước Ngủ", description: "Viết ra giúp giảm vòng lặp.", howTo: "Viết 5 phút: điều lo + một bước hành động cho ngày mai." }, { title: "2. Đặt Khung Giờ Lo Lắng", description: "Đưa lo lắng về ban ngày.", howTo: "Dành 15 phút buổi chiều để xem lại các lo lắng." }, { title: "3. Gắn Nhãn Suy Nghĩ", description: "Không chống lại, hãy tạo khoảng cách.", howTo: "Nói: 'Tôi đang có suy nghĩ rằng...' rồi quay lại hơi thở." }, { title: "4. Câu Neo Khi Ngủ", description: "Câu lặp giúp giảm lang thang nhận thức.", howTo: "Lặp một câu trung tính theo mỗi lần thở ra 2-3 phút." }, { title: "5. Tỉnh >20 Phút thì Reset", description: "Nằm bực bội trên giường làm não học thức.", howTo: "Ra khỏi giường tạm thời, ánh sáng thấp, làm việc nhẹ rồi quay lại khi buồn ngủ." }, { title: "6. Giảm Đầu Vào Thông Tin Muộn", description: "Tin tức/mạng xã hội làm tăng kích hoạt nhận thức.", howTo: "Ngắt digital ít nhất 45 phút trước ngủ." }], buildingResilience: { title: "Kế Hoạch Ổn Định Ban Đêm", strategies: [{ label: "Giữ cùng thứ tự", text: "Tính dự đoán giúp não cảm thấy an toàn." }, { label: "Đo quy trình", text: "Theo dõi có làm routine hay không, không chỉ kết quả ngủ." }, { label: "Hỗ trợ ban ngày", text: "Điều hòa stress ban ngày giảm overthinking ban đêm." }] }, conclusion: { title: "Tâm Trí Yên Tĩnh Là Kỹ Năng", text: "Bạn không thể tranh luận để ngủ. Hãy dùng cấu trúc, lặp lại và chuyển hướng nhẹ nhàng." } } },
  "zh-CN": { category: "心理健康", title: "如何停止夜间过度思考：6个循证技巧", subtitle: "如果一到晚上脑子更吵，并不说明你有问题。这很常见，也可以训练改善。", date: "2026年4月7日", readTime: "8分钟阅读", backToPost: "返回博客", continueReading: "继续阅读", downloadCTA: { title: "用ShineMind安静思绪", subtitle: "通过睡前引导音频和写作提示，减少夜间心理噪音。", button: "下载ShineMind" }, relatedPosts: { anxiety: "如何管理焦虑：8种有效的循证技术", anxietyDesc: "白天与夜晚都建立稳定感 ->", journal: "如何开始感恩日记", journalDesc: "通过写作清理思维杂讯 ->" }, content: { whyMatters: { title: "为什么夜间更容易反刍", intro: "夜晚外部刺激减少，未解决想法更突出。疲劳也会削弱认知控制，让担忧循环更容易出现。" }, science: { title: "有效方法", description: "认知去融合、担忧时段、表达性书写、呼吸调节和刺激控制都被用于焦虑与失眠干预。" }, techniques: [{ title: "1. 睡前脑内清单", description: "写下来可降低心理负荷。", howTo: "5分钟写下担忧，并给每条配一个明天可执行动作。" }, { title: "2. 设定担忧窗口", description: "把担忧放在白天，而不是上床后。", howTo: "下午固定15分钟做担忧回顾。" }, { title: "3. 给想法贴标签", description: "不要硬抗，先拉开距离。", howTo: "对自己说：'我正在有一个想法是...' 然后回到呼吸。" }, { title: "4. 睡眠锚定短语", description: "重复短语可减少思绪游走。", howTo: "配合呼气缓慢重复中性短句2-3分钟。" }, { title: "5. 清醒超过20分钟就重置", description: "烦躁地躺着会强化清醒关联。", howTo: "短暂离床，低照明做安静活动，困了再回床。" }, { title: "6. 减少晚间信息输入", description: "新闻和社媒会提升认知唤醒。", howTo: "睡前至少45分钟停止数字输入。" }], buildingResilience: { title: "夜间稳定计划", strategies: [{ label: "每晚同一顺序", text: "可预测性会给大脑安全信号。" }, { label: "追踪过程指标", text: "记录是否执行流程，不只看睡眠结果。" }, { label: "白天先减压", text: "白天压力调节会显著影响夜间反刍。" }] }, conclusion: { title: "安静思绪是训练出来的", text: "你无法靠争辩入睡。结构、重复和温和回引，才是长期有效路径。" } } },
  "zh-TW": { category: "心理健康", title: "如何停止夜間過度思考：6個循證技巧", subtitle: "如果一到晚上腦子更吵，並不代表你有問題。這很常見，也可以訓練改善。", date: "2026年4月7日", readTime: "8分鐘閱讀", backToPost: "返回部落格", continueReading: "繼續閱讀", downloadCTA: { title: "用ShineMind安靜思緒", subtitle: "透過睡前引導音訊和寫作提示，減少夜間心理噪音。", button: "下載ShineMind" }, relatedPosts: { anxiety: "如何管理焦慮：8種有效的循證技術", anxietyDesc: "白天與夜晚都建立穩定感 ->", journal: "如何開始感恩日記", journalDesc: "透過寫作清理思維雜訊 ->" }, content: { whyMatters: { title: "為什麼夜間更容易反芻", intro: "夜晚外部刺激減少，未解決想法更突出。疲勞也會削弱認知控制。" }, science: { title: "有效方法", description: "認知去融合、擔憂時段、表達性書寫、呼吸調節和刺激控制都常用於焦慮與失眠方案。" }, techniques: [{ title: "1. 睡前腦內清單", description: "寫下來可降低心理負荷。", howTo: "5分鐘寫下擔憂，並配一個明天可執行動作。" }, { title: "2. 設定擔憂窗口", description: "把擔憂放在白天。", howTo: "下午固定15分鐘做擔憂回顧。" }, { title: "3. 給想法貼標籤", description: "不要硬抗，先拉開距離。", howTo: "說：『我正在有一個想法是...』再回到呼吸。" }, { title: "4. 睡眠錨定短語", description: "重複短語可降低思緒飄移。", howTo: "配合呼氣重複中性短句2-3分鐘。" }, { title: "5. 清醒超過20分鐘就重置", description: "焦躁躺床會強化清醒連結。", howTo: "短暫離床，低照明做安靜活動，困了再回床。" }, { title: "6. 減少晚間資訊輸入", description: "新聞和社媒會提高認知喚醒。", howTo: "睡前至少45分鐘停止數位輸入。" }], buildingResilience: { title: "夜間穩定計畫", strategies: [{ label: "每晚同一順序", text: "可預測性會給大腦安全訊號。" }, { label: "追蹤過程指標", text: "記錄是否執行流程，不只看睡眠結果。" }, { label: "白天先減壓", text: "白天調節壓力可減少夜間反芻。" }] }, conclusion: { title: "安靜思緒是可訓練的", text: "你無法靠爭辯入睡。結構、重複與溫和回引才有效。" } } }
};
